Repository HuskyGameDev/2017-team6, pull requests merged in 2018-03, with the labels that each got.

#78 Inventory Management
  Assets/Blender/Item_Medkit.blend
  Assets/Blender/Item_Medkit.blend.meta
  Assets/Blender/Item_Medkit.blend1
  Assets/Blender/Item_Medkit.blend1.meta
  Assets/Blender/Materials/MedkitMat.mat
  Assets/Blender/Materials/MedkitMat.mat.meta
  Assets/Prefabs/Drops/Drop_Lazer.prefab
  Assets/Prefabs/Drops/Material_Energy.prefab
  Assets/Prefabs/Drops/Material_Scrap.prefab
  Assets/Prefabs/Drops/Material_Wire.prefab
  Assets/Prefabs/Med Kit.prefab
  Assets/Prefabs/Med Kit.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/PlayerUI.prefab
  Assets/Prefabs/Weapons/Pistol.prefab
  Assets/Scenes/Jessie/jessie_dev2.unity
  Assets/Scripts/Enemies/EnemyAttack.cs
  Assets/Scripts/Enemies/EnemyManager.cs
  Assets/Scripts/GameUI.cs
  Assets/Scripts/MedKit.cs
  Assets/Scripts/MedKit.cs.meta
  Assets/Scripts/Player/Hotbar.cs
  Assets/Scripts/Player/Inventory.cs
  Assets/Scripts/Player/Item.cs
  Assets/Scripts/Player/PlayerManager.cs
  Assets/Scripts/Player/PlayerUse.cs
  Assets/Scripts/UI_Game.cs
  Assets/Scripts/UI_Game.cs.meta
  Assets/Scripts/UI_Item.cs
  Assets/Scripts/UI_Item.cs.meta
  Assets/Scripts/UI_Tooltip.cs
  Assets/Scripts/UI_Tooltip.cs.meta
  Assets/Scripts/UnitManager.cs
  Assets/Scripts/UnitManager.cs.meta
  Assets/Scripts/Weapon/HitscanWeapon.cs
  Assets/Scripts/Weapon/ProjectileWeapon.cs
  Assets/Scripts/Weapon/Weapon.cs
  Assets/Sprites/i_medkit.png
  Assets/Sprites/i_medkit.png.meta
  ProjectSettings/InputManager.asset
Labels: Done

#80 New toaster enemy
  Assets/Blender/Toaster.prefab
  Assets/Blender/Toaster.prefab.meta
  Assets/Blender/toaster.blend
  Assets/Blender/toaster.blend.meta
  Assets/Scripts/Enemies/EnemyManager.cs
  Assets/Scripts/Enemies/EnemyMovement.cs
  Assets/Scripts/Weapon/BasicBullet.cs
Labels: Work In Progress

#84 Ddded more variability to drop location and fixed drop location
  Assets/Scripts/Enemies/EnemyManager.cs
Labels: Bug!, Done

#86 Added melee damage to toaster enemy so it actually does something.
  Assets/Collision_Damage.cs
  Assets/Collision_Damage.cs.meta
  Assets/Scripts/Enemies/EnemyManager.cs
Labels: Done, Update
